### ISSUE TITLE
Code of conduct

### ISSUE THREAD

**Issue by moggers87** [moggers87/salmon#107]
I'll be adding [The Contributor Covenant Code of Conduct](https://www.contributor-covenant.org/) to this repo as it basically sums up how I think this project should be run (and hopefully it lines up with how you all think this project has been run so far).

**Comment by paulie-g** [comment]
Your profile picture can be regarded as violating your proposed COC given a sufficiently uncharitable attitude (hint: people who advocate for COCs are universally given to being uncharitable). Perhaps it's a sign that the value of virtue signaling by adding it is exceeded by the practical and philosophical marginal disutility of imposing a charter enabling opportunistic offence takers to exercise coercion on a *free* software project? Just a thought.

I'm just passing through, mind you, but in general I don't participate in projects that adopt it on principle. I know many devs who feel the same, but won't say it out loud. Good luck with your project.

**Comment by moggers87** [comment]
Please don't comment on this issue if you're just "passing through" :+1:
