### ISSUE TITLE
Port Old Lamson Docs to Salmon

### ISSUE THREAD

**Issue by tflink** [moggers87/salmon#27]
I'm in the process of converting the old Lamson docs (from the old gpl3 version that salmon was forked from ) into rst in the form of a sphinx project so it can be deployed as a rtd project or through github sites.

I still need to do some tweaking and cleanup to match changes in salmon since the fork but before I put too much more work into tweaking stuff, I wanted to see if there's an interest in such a PR

**Comment by moggers87** [comment]
From what I remember, they weren't very good. And if they're anything like the code comments, they probably don't agree with what the code actually does ;)

Someone will also need to have a look into the license of the docs too - the code is GPLv3 but that doesn't mean the docs are.

**Comment by tflink** [comment]
From what I've been reading, they aren't that bad in terms of the content they cover. I haven't actually tried any of the stuff discussed in them yet, though. I want to learn salmon and figured working on the docs was a good place to start.

Is it worth bulding api docs from the docstrings if the comments are that inaccurate?

Verifying the docs license was on my todo list - thanks for the reminder. I'll update this ticket with my findings.

The other stuff on my todo list:
* check licensing on the docs to verify that they are gpl3 or at least gpl3 compatible
* update all the old easy_install commands with pip
* verify all the links are up-to-date and not dead
* remove docs that are no longer relevant
* figure out if the examples work now that I've done s/lamson/salmon
* other editing, cleanup for style etc.

**Comment by tflink** [comment]
Looking through the last-lamson tag, I only see one reference to copyright in the docs and that's in the html templates used to render the docs:
`Lamson Project(TM) and all material on this site Copyright &copy; 2009 <a href="http://zedshaw.com/" title="Zed Shaw's blog">Zed Shaw</a> unless otherwise stated.<br/>`

This shows up in the following places that I found:
* doc/lamsonproject.org/template.html
* doc/lamsonproject.org/input/*.html
* doc/lamsonproject.org/output/*.html

However, I see no other reference to license outside of the "BSD or GPL3" license in the project's root. I interpret this to mean that the docs are licensed under those same licenses and are usable. Are there other opinions/interpretations?

**Comment by moggers87** [comment]
As the docs aren't really part of the software, I'm not convinced. I'd really like to have documentation that's properly licensed.

**Comment by tflink** [comment]
I agree completely on the properly licensed documentation part - I don't want to cause licensing issues.

I'm still under the opinion that the documentation is gpl3 since it's in a subfolder of the main repo that has the license file in it but I'm not sure it matters because I didn't think about how the gpl would apply to documentation. One thing I did find was the SFLC's [A Legal Issues Primer for Open Source and Free Software Projects](https://www.softwarefreedom.org/resources/2008/foss-primer.html#x1-120002.4) in which they state:

> Keep in mind that the licenses discussed above were specifically designed for software projects and sometimes have strange and confusing implications when applied to non-software works.

Even if the docs are covered under gpl3, that will affect any directive work and without the original author's permission, that license couldn't be changed to something that makes more sense for documentation (CC, GFDL etc.).

It sounds like a clean room restart for the documentation would at least be wise (with my interpretation of the license for the old docs) or required (with your interpretation of the license for the old docs) and this ticket can be closed. I'll create a new one when I have new docs ready for a PR
