### ISSUE TITLE
Replace modargs

### ISSUE THREAD

**Issue by moggers87** [moggers87/salmon#28]
Upstream looks dead, probably hasn't got Py3k support.

**Comment by tino** [comment]
I always perceived the commandline argument style of modargs as weird, so good idea :). I would suggest http://docopt.org/, made my life quite a lot easier...

**Comment by moggers87** [comment]
TODO: unittest argparse objects too
TODO: sanitise help and options

**Comment by moggers87** [comment]
Done.
