### ISSUE TITLE
Configuration of the server

### ISSUE THREAD

**Issue by Jzarecta** [moggers87/salmon#31]
Is there any documentation on how to get this server up and running, I went to the lamson server site, but is down, and there doesnt seem to be a backup of the documentation on the wiki of the github project either.

**Comment by tino** [comment]
There isn't. There was some discussion going on about docs: #27, but nothing yet.

I started converting the old docs to Sphinx here: https://github.com/tino/salmon/tree/feature/sphinx-docs, and although it is not an option to include them here (see #30), it might help you to more easily read the old docs. I did not convert everything correctly to restructured text yet, but you can check the branch out, install Sphinx, ``make html`` and see if it helps you.

**Comment by moggers87** [comment]
FYI there are now docs and I have written a very short "getting started" page. See #33

**Comment by tino** [comment]
:+1:
