### ISSUE TITLE
pep8 no longer imposes 80 char

### ISSUE THREAD

**Issue by WnP** [moggers87/salmon#39]
from [pep8 maximum line length section](https://www.python.org/dev/peps/pep-0008/#maximum-line-length):

> it is okay to increase the nominal line length from 80 to 100 characters (effectively increasing the maximum length to 99 characters)

[since 01 Aug 2013](https://hg.python.org/peps/rev/bd8c95ad2054)

**Comment by moggers87** [comment]
Not sure I understand what this issue is about - I don't follow PEP8's length recommendations (as stated in the README)

**Comment by WnP** [comment]
the README said
> the 80 character limit it -pep8- imposes

but pep8 doesn't imposes a 80 character limit
that's all about this issue :)

**Comment by moggers87** [comment]
I'm closing this as:

* 80 is still the suggested limit
* I'm still ignoring PEP8's optional max-length extension

**Comment by WnP** [comment]
Yes, "suggested" not "imposed"…
> … and the Words made the world.
