### ISSUE TITLE
Unable to change subject

### ISSUE THREAD

**Issue by jluttine** [moggers87/salmon#44]
I might be doing something totally wrong here, but at least to my understanding this handler should just change the subject and send the email to me:

```
import logging
from salmon.routing import route, stateless
from config.settings import relay

@route("(address)@(host)", address=".+", host=".+")
@stateless
def START(message, address=None, host=None):

    logging.debug("Current subject: {0}".format(message['Subject']))
    message['Subject'] = 'New subject'
    logging.debug("New subject: {0}".format(message['Subject']))

    relay.deliver(message, To=['my.email.address@somewhere.com'])
```

However, `logs/salmon.log` shows that the subject doesn't change:
```
2016-05-23 12:33:50,559 - root - DEBUG - Current subject: original subject
2016-05-23 12:33:50,559 - root - DEBUG - New subject: original subject
```

And indeed, the message I receive has the original subject. Otherwise forwarding to my email address works.

How can I change/modify the subject field?

**Comment by jluttine** [comment]
This can be seen also as easily as:
```python
>>> from salmon.mail import MailResponse
>>> m = MailResponse(Subject='Foo')
>>> m['Subject']
u'Foo'
>>> m['Subject'] = 'Bar'
>>> m['Subject']
u'Foo'
```

**Comment by moggers87** [comment]
This is actually how Python's `email` package does things: https://docs.python.org/2/library/email.message.html#email.message.Message.__setitem__

However, there's no reason our wrapper should do things that way :)

**Comment by jluttine** [comment]
Thanks! That worked:
```python
del m['Subject']
m['Subject'] = 'New subject'
```
