### ISSUE TITLE
Gitter chat, IRC, mailing list or other discussion forum?

### ISSUE THREAD

**Issue by jluttine** [moggers87/salmon#45]
Is there some forum where it'd be possible to discuss and ask for help from others? Mailing list perhaps or IrC channel? If not, would you be interested in simply enabling gitter chat for this repo? I've found that very convenient. Or is it ok to ask for help via these github issues?

**Comment by moggers87** [comment]
I don't have a dedicated IRC channel, but you can find me in `#inboxen` on irc.megworld.co.uk (it's also where travis posts test results etc.)

Given the size of the porject, I'm happy people to ask questions in issues - it often brings up things that need to be documented.

**Comment by jluttine** [comment]
Asking questions in issues sounds good, thanks!
