### ISSUE TITLE
Question: How to ignore mail with unknown "To" host?

### ISSUE THREAD

**Issue by jluttine** [moggers87/salmon#46]
Not sure if this is a proper place to ask for questions/help (see #45).

I'm now wondering how I can just ignore emails which are sent to some other host than what I've specified.

My undeliverable queue fills up with some spam that my server receives. That spam is designated to some weird email addresses with weird hosts. I'd like just ignore the mail if the "To" host isn't one of my accepted host names (I have a few of them). Is there a place to list these valid hostnames or are they automatically parsed from the used handlers? And how then ignore mail that doesn't match these host names?

Anyway, thanks a ton for working on this Lamson fork, this is great.

**Comment by jluttine** [comment]
And how can I delete the mails in the undeliverable queue? I tried using `salmon queue` but I get `TypeError` with it:
```
$ salmon queue --count undeliverable
Traceback (most recent call last):
  File "/.../bin/salmon", line 9, in <module>
    load_entry_point('salmon-mail==2.99.99', 'console_scripts', 'salmon')()
  File "/.../lib/python2.7/site-packages/salmon/commands.py", line 75, in main
    cmd(**vars(args))
TypeError: command() got an unexpected keyword argument 'queue'
```

**Comment by jluttine** [comment]
And how can I "not handle" a mail in a handler? In some cases, the handler can't process the mail (unknown address most likely) and I'd like to put that mail to undeliverable queue. How to do that? Salmon log just says that the mail is handled after calling the handler. How can I say that the handler did not handle the mail? I tried googling but I only found my same old question on stackoverflow unanswered.

So many questions.. Sorry for troubling, and thanks for any help!

**Comment by moggers87** [comment]
If you raise an exception in the handler, it will end up in the undeliverable queue. You probably want to raise something like  `SMTPError(550, "Unknown address")` ([source](https://github.com/moggers87/salmon/blob/master/salmon/server.py#L39)) to tell the other side you haven't delivered the message.

As for non-matching spam, you should really run Salmon behind another mail server (e.g. Postfix or Exim) as you would run something like Django or Flask behind web server. For example, I use Postfix and tell it to only forward mail for particular domains to Salmon.

And thanks for contributing :)

**Comment by moggers87** [comment]
Oh, also: could you open a separate issue for the queue command? Thanks!

**Comment by jluttine** [comment]
Thanks for pointing out `SMTPError`. I still have a few more questions:

- If I send an email to both a valid and an invalid address, it seems that I get the SMTP error for the invalid address but not the valid address delivered. Doesn't sound right? I think I should get the error for the invalid address and the mail delivered for the valid address.

- Ok, I might take a look on Postfix or Exim. The host name based filtering would be sufficient for me and I thought that it'd be possible with Salmon, but it isn't? I'm now thinking about writing a spam handler which handles all hosts and addresses but does nothing, so if the other handlers haven't handled the mail, then that will do it silently. I'm just wondering what happens if another handler raises an error. In that case, I don't want the spam handler to handle the mail, but instead the mail to go to the undeliverable queue. Perhaps, I'll play a little bit and see what happens. But if you have any insight or helpful comments on this, they're greatly appreciated.

**Comment by jluttine** [comment]
Not sure if this is a bug, but it is a bit confusing at least: The following line can't be reached:
https://github.com/jluttine/salmon/blob/master/salmon/server.py#L199
So, I suppose if a handler raises `SMTPError`, the message won't go to the undeliverable queue (as it should?).

**Comment by moggers87** [comment]
Yeah, that's not meant to be there (take a look at the LMTPServer below). Good spot!

I'm at work right now, but I'll make time to answer your other questions this evening.

**Comment by moggers87** [comment]
> If I send an email to both a valid and an invalid address, it seems that I get the SMTP error for the invalid address but not the valid address delivered. Doesn't sound right? I think I should get the error for the invalid address and the mail delivered for the valid address.

Not sure I understand - the to TO address is the contents of the RCPT TO command given to Salmon by the client. There can (well, should) only be one.

> Ok, I might take a look on Postfix or Exim. The host name based filtering would be sufficient for me and I thought that it'd be possible with Salmon, but it isn't?

Salmon (and Lamson before it) was never designed to replace a traditional mail server. Things like rejecting mail that's not for your domain and dealing with bad clients are way out of scope for this project.

**Comment by jluttine** [comment]
Ok, I'm not familiar with mail servers, so I might be thinking this totally wrong. To be more specific, I sent an email to two addresses that should be both handled by my Salmon server. But in the logs I see:

```
2016-05-23 18:11:13,874 - root - DEBUG - Message received from Peer: ('###.###.###.###', #####), From: 'sender.address@somedomain.com', to To ['address1@mydomain.com', 'address2@mydomain.com'].
2016-05-23 18:11:13,875 - routing - DEBUG - Matched 'address1@mydomain.com' against START.
2016-05-23 18:11:14,449 - routing - DEBUG - Message to address1@mydomain.com was handled by app.handlers.myhandler.START
```

The `To` field contains two addresses which both should be handled but only the first one is handled.

So in order for this to be handled properly, do I need to have a traditional mail server in front of salmon, and this server would loop through the recipients and give them one by one to salmon? Or is there something else I'm doing wrong?

Thanks for the help!

Are there any instructions on how to put Salmon behind a traditional mail server

**Comment by moggers87** [comment]
Interesting! I see you've made #48 - I'll mark that as a bug.

**Comment by moggers87** [comment]
With regard to setting up Salmon behind another mail server, I personally use Postfix. [There are some docs for setting up a relaying mail server](http://www.postfix.org/STANDARD_CONFIGURATION_README.html#backup) but they're not exactly friendly. Hopefully that'll give you a start ☺

**Comment by moggers87** [comment]
OK, I think all your questions/bugs have been answered/fixed so I'll close this issue now.

Feel free to open more issues as you like ☺
