### ISSUE TITLE
Mail delivered to only one address

### ISSUE THREAD

**Issue by jluttine** [moggers87/salmon#48]
It seems that if the list of recipients contains several email addresses that Salmon needs to handle, it only handles one and delivers the mail there. At least I've been trying to send one email to several recipients and only one of them receives it each time.

**Comment by moggers87** [comment]
Looks like Salmon doesn't deal with multiple RCPT TO commands in the same SMTP transaction.

This will be a bit tricky to deal with as, unlike LMTP, SMTP will only return one return code after DATA. Tempted to just return an error on subsequent RCPT TOs (assuming that doesn't break standards)

**Comment by jluttine** [comment]
If it helps, I think this worked when I used Lamson. At least I often sent mail to several people with all addresses handled via Lamson and they all received the email (or at least most of them).

**Comment by moggers87** [comment]
`beff5633166bc4a2d20ad36d007e5beac6bff6de` is to blame - my assumption in that commit was clearly wrong. However, I don't think I will be bringing this feature back.

My main concern is what happens if a handler raises a SMTPError. For example:
```
@route("(local)@(domain)", local=".+", domain=".+")
def my_handler(message, local, domain):
    if Inbox.query(local=local):
        deliver_mail(message)
    else:
        raise SMTPError(450, "No such address")  # 450, let client to try again later
```

If the first recipient is valid but not the second, a client would retry because Salmon had returned a 450 at the end of transaction. This would result in a lot of duplicate messages for the first recipient.

I'll have a look at what SMTP clients do in the case of a non-250 response to RCPT TO.

**Comment by jluttine** [comment]
Ok, I'm not familiar with mail servers, so I don't know how this works in other mail server systems. Do you have any suggestions what would be the correct way to handle multiple recipients with Salmon? Have another mail server in front and that loops over the recipients and uses Salmon for each of those?

**Comment by moggers87** [comment]
The two differences between Salmon and a traditional mail server are:

1. Salmon doesn't separate checking it can deliver and actual delivery - it all happens at once
2. Salmon does none of this in a transactional manner, so it can't rollback in the example above (and how could it given that handlers are user provided)

If you need multiple recipients you can either tell your internet facing mail server to deliver multiple times with one recipient per connection (e.g. Postfix has an option called `smtp_destination_recipient_limit`).

Alternatively, you could use `LMTPServer`. This side steps this issue completely by returning multiple response codes at the end of `DATA`. [RFC 2033](https://tools.ietf.org/html/rfc2033) is worth a read IMO.

Fair warning: I've never used it in production, so I look forward to your bug reports ;)

**Comment by moggers87** [comment]
Sorry, that should have been `LMTPReceiver`.
