### ISSUE TITLE
Relay deliver eats connection error without reraising the exception

### ISSUE THREAD

**Issue by DrDub** [moggers87/salmon#49]
This line:

https://github.com/moggers87/salmon/blob/master/salmon/server.py#L128

shouldn't it reraise the exception?

Otherwise the email is never delivered and no indication of this fact is given to the sender.

**Comment by moggers87** [comment]
Previously, I would have said no because I wanted to maintain compatibility with Lamon. However, such thoughts have gone out the window :)

Thanks for the report.
