### ISSUE TITLE
Release 3.0.0

### ISSUE THREAD

**Issue by jluttine** [moggers87/salmon#52]
Thanks for this great project! I noticed there hasn't been a release in a while, last one is version 2, from 20 Jun 2014. Almost three years old.. Would you like to make a new release? Or is the state after every commit equally stable and ready for production? If you'll make releases, may I suggest using semantic versioning so it's easy to notice, for instance, if the API changes in possibly backwards incompatible ways.

**Comment by moggers87** [comment]
We have this milestone: https://github.com/moggers87/salmon/milestone/1 - I'd like to get a few more of those done before I start thinking about a release.

And yes, I plan on using more traditional version numbers in future.

**Comment by jluttine** [comment]
Ok, nice! Thanks for the info!

**Comment by moggers87** [comment]
Code-wise, I'm fairly happy with releasing what we've got in master as 3.0.0.

However, I'd like to get the docs a bit more complete (there are some sections still missing)

**Comment by moggers87** [comment]
Ha! Spoke too soon. Writing the docs has revealed some inconsistencies in the API that I really don't like.

**Comment by moggers87** [comment]
Release candidate: https://pypi.python.org/pypi/salmon-mail/3.0.0rc1

**Comment by moggers87** [comment]
Final release: https://pypi.python.org/pypi/salmon-mail/3.0.0
