### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by moggers87** [moggers87/salmon#7]
Python 3 support would be a great selling point

**Comment by moggers87** [comment]
python-daemon now has py3k support, waiting on #28 now

**Comment by moggers87** [comment]
https://travis-ci.org/moggers87/salmon/builds/72724253

**Comment by moggers87** [comment]
Dependencies install under Python 3 (yay), but Python Daemon doesn't install under 2.6. I need to find out if this is intended or not.

**Comment by moggers87** [comment]
While chasing down various encoding issues, I stumbled upon this: https://bugs.python.org/issue19662

tl;dr: Python's SMTPd is absolutely useless in anything less than 3.5 (assuming the above patch made it into the 3.5 release)

I'll probably end up bundling 3.5's `smtpd.py` and conditionally import it.

**Comment by moggers87** [comment]
Actually, maybe monkey patching would be better - it means that I won't end up doing the work twice (once here and once in lmtpd)

**Comment by moggers87** [comment]
This is currently stalled as I'm trying to get my head around changes in the email package

**Comment by moggers87** [comment]
Now that Python 3.5 is out and I've moved away from pre-processing emails (see #40 ), maybe it's a good time to have another look at this?

**Comment by moggers87** [comment]
https://travis-ci.org/moggers87/salmon/builds/238873373

Still having issues with python-daemon (as ever). I think might need to pin on an older version.

**Comment by Juanlu001** [comment]
Awesome! Thank you very much for your work on this :) Is there a chance we can have a prerelease to try salmon out?

**Comment by moggers87** [comment]
You can install master via pip:

```
pip install git+https://github.com/moggers87/salmon.git@7cb96c40a9e038ceefb7f25d8f5010b82a6a23fd
```

I don't see a release happening any time soon (docs need completing for a start) and as long as you're pinning to a specific commit it's quite safe to install from git this way.

**Comment by Juanlu001** [comment]
Fair enough, thanks! :+1:
