### ISSUE TITLE
How to set up as a simple mail server?

### ISSUE THREAD

**Issue by jluttine** [moggers87/salmon#70]
I'm trying to set up a very simple mail server: listen to emails for a particular domain, determine whom it should be sent to based on the address and send the email using ISP mail server as a relay. A very simple mailing list server.

This was very easy with Lamson. With Salmon, there was a bug(?) in SMTPReceiver that only one recipient was handled. With LMTPReceiver (which is now the default), this is fixed but now there is suddenly the nightmare of setting up a mail server gateway in front of Salmon. The main reason to use Lamson/Salmon - at least for me - was to avoid setting up and maintaining these huge massive complex mail servers and just have a very simple process running and doing the simple thing. Or perhaps I'm missing something and it should be as easy with Salmon too somehow? I'm a bit confused on how Salmon is supposed to be used.. The only instructions I found were: "Salmon is best deployed behind another mailserver such as Postfix or Sendmail - much in the same way as you host a WSGI application behind Apache or Nginx."

For these reasons, I would really appreciate some help on how to set up Salmon so that it works as a mail server. If that really requires some mail server gateway in front, then it'd be great to have some instructions or at least pointers on how to achieve this in a very lightweight way. I don't need mailboxes, I don't need mail sending server (I use my ISP mail server as a relay). If you have any ideas how to proceed, I'd be really happy to hear. If I get it working, I could perhaps write some instructions in case that's useful for other users. Anyway, thanks for this great package and your efforts!

**Comment by jluttine** [comment]
Hmm.. Could I put Salmon SMTP receiver in front of the LMTP receiver, that is, have two separate Salmon processes running? That might be quite simple. I'd just need to figure out how the SMTP receiver should forward the emails to the LMTP receiver.

**Comment by moggers87** [comment]
The Lamson docs are no longer available, but I'm fairly certain that they strongly recommended deploying in the same fashion as Salmon.

Salmon's SMTP receiver does not implement anything like TLS or connection limiting, so keep that in mind. It will work, but don't open an issue later about your server crashing or someone has been reading your mail ;)

As for documenting how to setup Postfix, I don't want that in the documentation as Postfix is itself quite badly documented and it's too easy to misconfigure it and create an open-relay. I'll open up the wiki on this repo and see if I have time to start a page on Postfix config.

**Comment by jluttine** [comment]
Ok, thanks! Those are the reasons I wouldn't want to set up Postfix.. :) Maybe some others are easier? Exim or dovecot? How have you set this up yourself?

Regarding documentation, for instance with Django, there is documentation on how to set up the parts that are relevant to Django in uwsgi and nginx/apache/... configuration. I think it would be nice to have some instructions like "put this and this configuration to this value and it should work with Salmon" or "these are the configurations values you need to set and you might want to disable this and this if you're just using this as a gateway in front of Salmon alone".

**Comment by jluttine** [comment]
Pheeew! I think I finally got it working! (At least I think so.)

I use Postfix as a SMTP mail gateway on the same server as Salmon LMTP is running.

For Salmon, I use relay settings according to my ISP SMTP settings and receiver settings `host="0.0.0.0"` and `port=8823`.

For Postfix, I don't use any local mail boxes, just forward email to Salmon. Also, I don't use Postfix to send email to the internet, I use my ISP for that. Here are the relevant bits:

In `/etc/postfix/main.cf`:

```
# Disable local delivery
mydestination =
local_recipient_maps =
local_transport = error: local main delivery disabled
# Hostname from the MX record
myhostname = mail.example.com
# Relay all @example.com emails to Salmon
transport_maps = hash:/etc/postfix/transport
relay_domains = example.com
relay_recipient_maps = hash:/etc/postfix/relay_recipients
# Obviously, the file contains lots of other configurations too
# ....
```

`/etc/postfix/transport`:
```
example.com lmtp:localhost:8823
```

`/etc/postfix/relay_recipients`:
```
@example.com x
```

As I'm not familiar with email servers and this was the first time I'm configuring anything like this, it's possible that there's something (terribly) wrong. Feedback is most welcome.

**Comment by moggers87** [comment]
Looks good! However, I'd recommend removing `transport_maps` and `relay_recipient_maps` and replace them with `relay_transport = lmtp:127.0.0.1:8823` to make your config more readable. It keeps everything in one file and you'll only have to update one line if you change or add additional domain names in future.

Would you like to add this to [the wiki](https://github.com/moggers87/salmon/wiki)? It'll probably be quite useful for other users.

**Comment by jluttine** [comment]
Done: https://github.com/moggers87/salmon/wiki/Configuring-the-mail-server
